### ISSUE TITLE
Can you provide data preprocessing code?

### ISSUE THREAD

**Issue by XChuckie** [zeng-zhen/SCD#1]
Hey, Author! I am interested in your work on long-tail in cognitive diagnosis. However, I'm having trouble running this experimental data in the context of other data distributions. Can you provide some data preprocessing code? My email is chenaoxia168@gmail.com. Thank you!

**Comment by zeng-zhen** [comment]
Our work follows  [RCD](https://github.com/bigdata-ustc/RCD) and refer to their code, you can use the code they provided.

**Comment by XChuckie** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        OK！Another question：why did you not use AUC as an evaluation indicator?Can you answer this question? Thank you very much！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/30/2023 20:03
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zeng-zhen/SCD] Can you provide data preprocessing code? (Issue #1)
        
      
    
  
  
Our work follows  RCD and refer to their code, you can use the code they provided.

**Comment by zeng-zhen** [comment]
Our method has also improved in AUC, which we did not present in the paper due to space limitations.

**Comment by XChuckie** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    OK!Thank you!
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/30/2023 20:14
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [zeng-zhen/SCD] Can you provide data preprocessing code? (Issue #1)
        
      
    
  
  
Our method has also improved in AUC, which we did not present in the paper due to space limitations.
